# Generated by Django 5.1.7 on 2025-03-24 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino'), ('other', 'Otro')], max_length=10, verbose_name='Género')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contacto')),
                ('left_kidney_image', models.ImageField(blank=True, null=True, upload_to='patient_images/', verbose_name='Imagen del Riñón Izquierdo')),
                ('right_kidney_image', models.ImageField(blank=True, null=True, upload_to='patient_images/', verbose_name='Imagen del Riñón Derecho')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
